background {{ colors.background.default.hex }}
foreground {{ colors.on_background.default.hex }}
cursor {{ colors.on_background.default.hex }}
cursor_text_color {{ colors.background.default.hex }}
selection_background {{ colors.on_secondary_container.default.hex }}
selection_foreground {{ colors.secondary_container.default.hex }}

color0 {{ colors.background.default.hex }}
color1 {{ "#FF6188" | to_color | blend: {{ colors.primary.default.hex }}, 0.85 | saturate: -20.0, "hsl" | auto_lightness: 25.0 }}
color2 {{ "#A9DC76" | to_color | blend: {{ colors.primary.default.hex }}, 0.85 | saturate: -20.0, "hsl" | auto_lightness: 25.0 }}
color3 {{ "#FC9867" | to_color | blend: {{ colors.primary.default.hex }}, 0.85 | saturate: -20.0, "hsl" | auto_lightness: 25.0 }}
color4 {{ "#FFD866" | to_color | blend: {{ colors.primary.default.hex }}, 0.85 | saturate: -20.0, "hsl" | auto_lightness: 25.0 }}
color5 {{ "#F47FD4" | to_color | blend: {{ colors.primary.default.hex }}, 0.85 | saturate: -20.0, "hsl" | auto_lightness: 25.0 }}
color6 {{ "#78DCE8" | to_color | blend: {{ colors.primary.default.hex }}, 0.85 | saturate: -20.0, "hsl" | auto_lightness: 25.0 }}
color7 {{ colors.on_background.default.hex }}
color8 {{ "#121212" | to_color | blend: {{ colors.primary.default.hex }}, 0.85 | saturate: -20.0, "hsl" | auto_lightness: 15.0 }}
color9 {{ "#FF6188" | to_color | blend: {{ colors.primary.default.hex }}, 0.85 | saturate: -20.0, "hsl" | auto_lightness: 15.0 }}
color10 {{ "#A9DC76" | to_color | blend: {{ colors.primary.default.hex }}, 0.85 | saturate: -20.0, "hsl" | auto_lightness: 15.0 }}
color11 {{ "#FC9867" | to_color | blend: {{ colors.primary.default.hex }}, 0.85 | saturate: -20.0, "hsl" | auto_lightness: 15.0 }}
color12 {{ "#FFD866" | to_color | blend: {{ colors.primary.default.hex }}, 0.85 | saturate: -20.0, "hsl" | auto_lightness: 15.0 }}
color13 {{ "#F47FD4" | to_color | blend: {{ colors.primary.default.hex }}, 0.85 | saturate: -20.0, "hsl" | auto_lightness: 15.0 }}
color14 {{ "#78DCE8" | to_color | blend: {{ colors.primary.default.hex }}, 0.85 | saturate: -20.0, "hsl" | auto_lightness: 15.0 }}
color15 {{ "#333034" | to_color | blend: {{ colors.primary.default.hex }}, 0.85 | saturate: -20.0, "hsl" | auto_lightness: 15.0 }}
color16 {{ "#D65D0E" | to_color | blend: {{ colors.primary.default.hex }}, 0.85 | saturate: -20.0, "hsl" | auto_lightness: 15.0 }}
color17 {{ "#A89984" | to_color | blend: {{ colors.primary.default.hex }}, 0.85 | saturate: -20.0, "hsl" | auto_lightness: 15.0 }}
color18 {{ "#D79921" | to_color | blend: {{ colors.primary.default.hex }}, 0.85 | saturate: -20.0, "hsl" | auto_lightness: 15.0 }}

# --- Tab bar settings synced with Matugen ---
active_tab_foreground {{ colors.surface.default.hex }}
active_tab_background {{ colors.primary.default.hex }}
inactive_tab_foreground {{ colors.on_surface_variant.default.hex }}
inactive_tab_background {{ colors.surface_container.default.hex }}
tab_bar_background {{ colors.surface.default.hex }}
